# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Invoke-WebRequest -Uri 'http://sonarcloud.io/static/cpp/build-wrapper-win-x86.zip' -OutFile 'build-wrapper.zip'
      Expand-Archive -Path 'build-wrapper.zip' -DestinationPath '.'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'colinmuellertest'
    scannerMode: 'MSBuild'
    projectKey: 'CPPMix'
    projectName: 'CPPMix'
    extraProperties: 'sonar.cfamily.build-wrapper-output=bw-output'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'build-wrapper-win-x86/build-wrapper-win-x86-64.exe --out-dir bw-output dotnet build'

- task: SonarCloudAnalyze@1